/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFramePrincipal.java
 *
 * Created on 28 févr. 2012, 16:21:55
 */

package predictifIHM;

import Service.Service;

/**
 *
 * @author Administrateur
 */
public class JFrameConnexion extends javax.swing.JFrame {

    private Service service;
    private JFramePrincipal principalFrame;
    /** Creates new form JFrameConnexion */
    public JFrameConnexion() {
        initComponents();
        jLabelErreur.setVisible(false);
        service = new Service();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNuméro = new javax.swing.JLabel();
        jLabelMotdePasse = new javax.swing.JLabel();
        jPasswordFieldMotdepasse = new javax.swing.JPasswordField();
        jButtonConnection = new javax.swing.JButton();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelErreur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNuméro.setText("Numéro d'employé");

        jLabelMotdePasse.setText("Mot de passe");

        jButtonConnection.setText("Se connecter");
        jButtonConnection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConnectionMouseClicked(evt);
            }
        });

        jTextFieldNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroActionPerformed(evt);
            }
        });

        jLabelErreur.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErreur.setText("Numéro ou mot de passe incorrect");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelErreur)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonConnection)
                        .addComponent(jPasswordFieldMotdepasse)
                        .addComponent(jLabelMotdePasse)
                        .addComponent(jLabelNuméro, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addComponent(jTextFieldNumero)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabelNuméro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabelMotdePasse)
                .addGap(18, 18, 18)
                .addComponent(jPasswordFieldMotdepasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonConnection)
                .addGap(18, 18, 18)
                .addComponent(jLabelErreur)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConnectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConnectionMouseClicked
        // TODO add your handling code here:
        if(!jTextFieldNumero.getText().isEmpty())
        {
            if(!jPasswordFieldMotdepasse.getText().isEmpty())
            {
                if(service.connectEmploye(Integer.parseInt(jTextFieldNumero.getText()), jPasswordFieldMotdepasse.getText()))
                {
                    jLabelErreur.setVisible(false);
                    if(principalFrame == null || (!principalFrame.isVisible()))
                    {
                        principalFrame = new JFramePrincipal(service);
                        principalFrame.setVisible(true);
                    }
                }
                else
                {
                    jLabelErreur.setVisible(true);
                }
            }
        }
}//GEN-LAST:event_jButtonConnectionMouseClicked

    private void jTextFieldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldNumeroActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameConnexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConnection;
    private javax.swing.JLabel jLabelErreur;
    private javax.swing.JLabel jLabelMotdePasse;
    private javax.swing.JLabel jLabelNuméro;
    private javax.swing.JPasswordField jPasswordFieldMotdepasse;
    private javax.swing.JTextField jTextFieldNumero;
    // End of variables declaration//GEN-END:variables

}
